### PR TITLE
URLが翻訳されている箇所を修正

### PR DESCRIPTION
**Pull request by kiyokura**
URLが翻訳されしまい誤ったものになってしまっているのを修正

### CODE REVIEW

**Comment by srvbpigh** [comment]
Hello, @kiyokura:

Thank you for your contribution! We are processing your suggestions and we will update you shortly.  

Kind regards, 

Microsoft DOCS Global Experience Team

**Comment by LisandroSu** [comment]
@kiyokura :

Thank you for your feedback and suggestion!

We agree with your suggestions, and we will include them into the next article update release.

Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by srvbpigh** [comment]
@kiyokura:

Thank you for your feedback and suggestion!

We agree with your suggestions, and we will include them into the next article update release.

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by srvbpigh** [comment]
@kiyokura:

Thank you for your feedback and suggestion!

We agree with your suggestions, and we will include them into the next article update release.

Kind regards,

Microsoft DOCS Global Experience Team

**Pull request merged**
